import React from "react";
import { createContext, useContext, useState } from "react";
import { useNavigate } from "react-router-dom";

const AppContext = createContext();

export const AppProvider = ({ children }) => {
  const navigate = useNavigate();
  const mockEvents = [
    {
      id: 1,
      title: "Civil Pudura",
      date: "11",
      month: "SEP",
      time: "5:00 PM",
      image:
        "https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&w=800",
      location: "Civil Engineering Dept",
      eventType: "Cultural",
      category: "weekdays",
      popularity: 87,
      createdAt: "2024-09-01",
      description: "An energetic cultural fest by Civil department.",
      likes: 124,
      price: 0,
      reviews: [
        {
          user: "Amit Sharma",
          rating: 5,
          comment: "Amazing event!",
          date: "2024-09-20",
        },
        {
          user: "Neha K.",
          rating: 4,
          comment: "Loved the vibes!",
          date: "2024-09-21",
        },
      ],
    },

    {
      id: 2,
      title: "Yaye Padura",
      date: "14",
      month: "SEP",
      time: "6:00 PM",
      image:
        "https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg?auto=compress&w=800",
      location: "Chemical Dept",
      eventType: "Cultural",
      category: "weekend",
      popularity: 93,
      createdAt: "2024-09-05",
      description: "A musical night filled with lights and excitement.",
      likes: 200,
      price: 199,
      reviews: [
        {
          user: "Rahul Verma",
          rating: 5,
          comment: "Unforgettable night!",
          date: "2024-09-22",
        },
      ],
    },

    {
      id: 3,
      title: "Spandana",
      date: "14",
      month: "SEP",
      time: "6:45 PM",
      image:
        "https://images.pexels.com/photos/1763067/pexels-photo-1763067.jpeg?auto=compress&w=800",
      location: "Medical Faculty",
      eventType: "Cultural",
      category: "weekdays",
      popularity: 74,
      createdAt: "2024-09-07",
      description: "A cultural event hosted by medical students.",
      likes: 95,
      price: 0,
      reviews: [],
    },

    {
      id: 4,
      title: "Devthon",
      date: "14",
      month: "SEP",
      time: "All Day",
      image:
        "https://images.pexels.com/photos/1181555/pexels-photo-1181555.jpeg?auto=compress&w=800",
      location: "CSE Dept",
      eventType: "Technical",
      category: "weekdays",
      popularity: 98,
      createdAt: "2024-09-10",
      description: "A thrilling 24-hour hackathon for passionate developers.",
      likes: 330,
      price: 0,
      reviews: [
        {
          user: "Karan Gupta",
          rating: 5,
          comment: "Best hackathon!",
          date: "2024-09-23",
        },
      ],
    },

    {
      id: 5,
      title: "RoboWars",
      date: "20",
      month: "SEP",
      time: "3:00 PM",
      image: "https://images.pexels.com/photos/712538/pexels-photo-712538.jpeg",
      location: "Mechanical Dept",
      eventType: "Technical",
      category: "weekend",
      popularity: 91,
      createdAt: "2024-09-11",
      description: "Robots battle for dominance in the arena.",
      likes: 260,
      price: 299,
      reviews: [],
    },

    {
      id: 6,
      title: "Sports Fiesta",
      date: "22",
      month: "SEP",
      time: "10:00 AM",
      image: "https://images.pexels.com/photos/399187/pexels-photo-399187.jpeg",
      location: "Stadium",
      eventType: "Sports",
      category: "weekdays",
      popularity: 60,
      createdAt: "2024-09-12",
      description: "Outdoor games and competitions.",
      likes: 80,
      price: 0,
      reviews: [],
    },

    {
      id: 7,
      title: "CodeSprint",
      date: "23",
      month: "SEP",
      time: "9:00 AM",
      image:
        "https://images.pexels.com/photos/3861964/pexels-photo-3861964.jpeg",
      location: "CSE Block",
      eventType: "Technical",
      category: "weekdays",
      popularity: 95,
      createdAt: "2024-09-13",
      description: "Competitive programming contest for coders.",
      likes: 310,
      price: 150,
      reviews: [],
    },

    {
      id: 8,
      title: "Dance Battle",
      date: "24",
      month: "SEP",
      time: "8:00 PM",
      image:
        "https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg",
      location: "Auditorium",
      eventType: "Cultural",
      category: "weekend",
      popularity: 85,
      createdAt: "2024-09-15",
      description: "Hip-hop and freestyle dance competition.",
      likes: 190,
      price: 0,
      reviews: [],
    },

    {
      id: 9,
      title: "Art Expo",
      date: "25",
      month: "SEP",
      time: "11:00 AM",
      image: "https://images.pexels.com/photos/707676/pexels-photo-707676.jpeg",
      location: "Arts Dept",
      eventType: "Cultural",
      category: "weekdays",
      popularity: 55,
      createdAt: "2024-09-16",
      description: "Artworks, paintings, and creative exhibitions.",
      likes: 75,
      price: 0,
      reviews: [],
    },

    {
      id: 10,
      title: "Circuit Debugging",
      date: "26",
      month: "SEP",
      time: "2:30 PM",
      image: "https://images.pexels.com/photos/256219/pexels-photo-256219.jpeg",
      location: "ECE Dept",
      eventType: "Technical",
      category: "weekdays",
      popularity: 88,
      createdAt: "2024-09-18",
      description: "Fix the electronic circuits under pressure.",
      likes: 145,
      price: 99,
      reviews: [],
    },

    {
      id: 11,
      title: "Math Olympiad",
      date: "27",
      month: "SEP",
      time: "1:00 PM",
      image: "https://images.pexels.com/photos/414579/pexels-photo-414579.jpeg",
      location: "Math Dept",
      eventType: "Technical",
      category: "weekdays",
      popularity: 78,
      createdAt: "2024-09-18",
      description: "Advanced math problems for top students.",
      likes: 110,
      price: 50,
      reviews: [],
    },

    {
      id: 12,
      title: "Fashion Walk",
      date: "28",
      month: "SEP",
      time: "7:00 PM",
      image:
        "https://images.pexels.com/photos/1964970/pexels-photo-1964970.jpeg",
      location: "Auditorium",
      eventType: "Cultural",
      category: "weekend",
      popularity: 82,
      createdAt: "2024-09-19",
      description: "Trendy fashion showcase by students.",
      likes: 165,
      price: 149,
      reviews: [],
    },

    {
      id: 13,
      title: "Cricket Tournament",
      date: "29",
      month: "SEP",
      time: "9:00 AM",
      image:
        "https://images.pexels.com/photos/1632090/pexels-photo-1632090.jpeg",
      location: "Ground",
      eventType: "Sports",
      category: "weekdays",
      popularity: 99,
      createdAt: "2024-09-20",
      description: "Inter-college cricket battle.",
      likes: 400,
      price: 0,
      reviews: [],
    },

    {
      id: 14,
      title: "Startup Pitch Fest",
      date: "30",
      month: "SEP",
      time: "4:00 PM",
      image:
        "https://images.pexels.com/photos/3184301/pexels-photo-3184301.jpeg",
      location: "Innovation Lab",
      eventType: "Technical",
      category: "weekend",
      popularity: 96,
      createdAt: "2024-09-22",
      description: "Pitch your startup idea to investors.",
      likes: 275,
      price: 399,
      reviews: [],
    },

    {
      id: 15,
      title: "Photography Walk",
      date: "01",
      month: "OCT",
      time: "6:00 AM",
      image: "https://images.pexels.com/photos/320617/pexels-photo-320617.jpeg",
      location: "Campus",
      eventType: "Cultural",
      category: "weekdays",
      popularity: 64,
      createdAt: "2024-09-23",
      description: "Capture nature and life around campus.",
      likes: 120,
      price: 0,
      reviews: [],
    },

    {
      id: 16,
      title: "Robotics Expo",
      date: "02",
      month: "OCT",
      time: "3:00 PM",
      image: "https://images.pexels.com/photos/58596/pexels-photo-58596.jpeg",
      location: "Workshop Hall",
      eventType: "Technical",
      category: "weekend",
      popularity: 86,
      createdAt: "2024-09-24",
      description: "Showcase your working robots.",
      likes: 140,
      price: 250,
      reviews: [],
    },

    {
      id: 17,
      title: "Kite Festival",
      date: "03",
      month: "OCT",
      time: "4:00 PM",
      image: "https://images.pexels.com/photos/58596/pexels-photo-58596.jpeg",
      location: "Main Ground",
      eventType: "Cultural",
      category: "weekend",
      popularity: 70,
      createdAt: "2024-09-25",
      description: "Colorful kites flying in the sky.",
      likes: 90,
      price: 0,
      reviews: [],
    },

    {
      id: 18,
      title: "AI Workshop",
      date: "05",
      month: "OCT",
      time: "10:00 AM",
      image:
        "https://images.pexels.com/photos/1181359/pexels-photo-1181359.jpeg",
      location: "Seminar Hall",
      eventType: "Technical",
      category: "weekdays",
      popularity: 97,
      createdAt: "2024-09-26",
      description: "Hands-on AI model building workshop.",
      likes: 310,
      price: 500,
      reviews: [],
    },

    {
      id: 19,
      title: "Music Fiesta",
      date: "07",
      month: "OCT",
      time: "7:30 PM",
      image:
        "https://images.pexels.com/photos/1190299/pexels-photo-1190299.jpeg",
      location: "Open Arena",
      eventType: "Cultural",
      category: "weekend",
      popularity: 90,
      createdAt: "2024-09-27",
      description: "Live singing and band performances.",
      likes: 180,
      price: 120,
      reviews: [],
    },

    {
      id: 20,
      title: "Chess Masterclass",
      date: "08",
      month: "OCT",
      time: "1:30 PM",
      image: "https://images.pexels.com/photos/58596/pexels-photo-58596.jpeg",
      location: "Library Hall",
      eventType: "Sports",
      category: "weekdays",
      popularity: 53,
      createdAt: "2024-09-28",
      description: "Learn strategy from expert chess players.",
      likes: 70,
      price: 0,
      reviews: [],
    },

    // ============================
    // UPCOMING EVENTS AFTER 29 NOV 2025
    // ============================

    {
      id: 101,
      title: "Tech Innovators Summit",
      date: "30",
      month: "NOV",
      time: "10:00 AM",
      image:
        "https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg",
      location: "Auditorium Hall A",
      eventType: "Technical",
      category: "weekdays",
      createdAt: "2025-11-30",
      likes: 50,
      popularity: 70,
      description:
        "A conference on emerging innovations and future technologies.",
      price: 0,
      reviews: [],
    },

    {
      id: 102,
      title: "Campus Winter Fest",
      date: "05",
      month: "DEC",
      time: "6:00 PM",
      image:
        "https://images.pexels.com/photos/3819960/pexels-photo-3819960.jpeg",
      location: "Central Ground",
      eventType: "Cultural",
      category: "weekend",
      createdAt: "2025-12-05",
      likes: 85,
      popularity: 90,
      description: "A night full of music, fun, stalls, and performances.",
      price: 149,
      reviews: [],
    },

    {
      id: 103,
      title: "AI & Robotics Bootcamp",
      date: "10",
      month: "DEC",
      time: "3:00 PM",
      image: "https://images.pexels.com/photos/3819960/pexels-photo-3819960.jpeg",
      location: "Tech Lab - Block C",
      eventType: "Technical",
      category: "weekdays",
      createdAt: "2025-12-10",
      likes: 110,
      popularity: 95,
      description: "Hands-on robotics and AI workshop for tech enthusiasts.",
      price: 499,
      reviews: [],
    },

    {
      id: 104,
      title: "Entrepreneurship Meetup",
      date: "12",
      month: "DEC",
      time: "4:30 PM",
      image:
        "https://images.pexels.com/photos/3183171/pexels-photo-3183171.jpeg",
      location: "Innovation Hub",
      eventType: "Technical",
      category: "weekdays",
      createdAt: "2025-12-12",
      likes: 92,
      popularity: 80,
      description: "Meet startup founders & investors. Pitch your ideas.",
      price: 300,
      reviews: [],
    },

    {
      id: 105,
      title: "Cultural Fusion Night",
      date: "15",
      month: "DEC",
      time: "7:00 PM",
      image:
        "https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg",
      location: "Open Theatre",
      eventType: "Cultural",
      category: "weekend",
      createdAt: "2025-12-15",
      likes: 120,
      popularity: 88,
      description: "Dance, music, drama & cultural fusion performances.",
      price: 99,
      reviews: [],
    },

    {
      id: 106,
      title: "Sports Mania 2025",
      date: "18",
      month: "DEC",
      time: "9:00 AM",
      image: "https://images.pexels.com/photos/399187/pexels-photo-399187.jpeg",
      location: "Sports Arena",
      eventType: "Sports",
      category: "weekdays",
      createdAt: "2025-12-18",
      likes: 76,
      popularity: 68,
      description: "Inter-college sports competition for all departments.",
      price: 0,
      reviews: [],
    },

    {
      id: 107,
      title: "Photography Contest",
      date: "20",
      month: "DEC",
      time: "11:30 AM",
      image: "https://images.pexels.com/photos/320617/pexels-photo-320617.jpeg",
      location: "Art Studio",
      eventType: "Cultural",
      category: "weekdays",
      createdAt: "2025-12-20",
      likes: 55,
      popularity: 58,
      description: "Showcase your photography skills and win exciting prizes.",
      price: 50,
      reviews: [],
    },

    {
      id: 108,
      title: "Winter Coding Marathon",
      date: "22",
      month: "DEC",
      time: "10:00 AM",
      image:
        "https://images.pexels.com/photos/3861964/pexels-photo-3861964.jpeg",
      location: "CSE Block",
      eventType: "Technical",
      category: "weekdays",
      createdAt: "2025-12-22",
      likes: 130,
      popularity: 99,
      description: "A full-day competitive coding marathon for developers.",
      price: 0,
      reviews: [],
    },

    {
      id: 109,
      title: "Christmas Carnival",
      date: "24",
      month: "DEC",
      time: "6:30 PM",
      image:
        "https://images.pexels.com/photos/3819967/pexels-photo-3819967.jpeg",
      location: "Main Campus",
      eventType: "Cultural",
      category: "weekend",
      createdAt: "2025-12-24",
      likes: 200,
      popularity: 100,
      description: "Food stalls, games, rides, Santa parade & live band.",
      price: 199,
      reviews: [],
    },

    {
      id: 110,
      title: "New Year Bash 2026",
      date: "31",
      month: "DEC",
      time: "11:00 PM",
      image:
        "https://images.pexels.com/photos/1190299/pexels-photo-1190299.jpeg",
      location: "Open Arena",
      eventType: "Cultural",
      category: "weekend",
      createdAt: "2025-12-31",
      likes: 350,
      popularity: 100,
      description:
        "DJ, fireworks, countdown & the biggest celebration of 2026.",
      price: 500,
      reviews: [],
    },
  ];

  const reviews = [
    {
      id: 1,
      name: "Taylor Swift",
      role: "Student, CSE",
      text: "Great way to discover events and never miss the important ones in campus.",
    },
    {
      id: 2,
      name: "Taylor Swift",
      role: "Club Coordinator",
      text: "Managing registrations became so simple. All data is in one place.",
    },
    {
      id: 3,
      name: "Taylor Swift",
      role: "Student, ECE",
      text: "Clean UI and easy event search. I love the reminders!",
    },
  ];
  const IconData = [
    { icon: "🎵", label: "Music Events" },
    { icon: "🎤", label: "Conferences" },
    { icon: "🎉", label: "Annual Celebrations" },
    { icon: "🎮", label: "Games" },
  ];

  return (
    <AppContext.Provider value={{ mockEvents, reviews, IconData, navigate }}>
      {children}
    </AppContext.Provider>
  );
};

export const useAppContext = () => {
  return useContext(AppContext);
};
